### ISSUE TITLE
Do we bother with PostgreSQL or just use the simpler sqlite3?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#28]
There is active discussion on the team whether we even need the power of a PostgreqSQL database for the "Service Area Budgets" card of our MVP (assuming this is the most likely application for us to launch at Demo Day).

At the moment we:

* have *no* scenarios in which users will submit data
* have no access control needs (all data will be available to any user hitting the API endpoints) to restrict tables or views
* are working with only a few hundred KB of data to be served up at max by any API response

Questions are:

* will this make it significantly harder in the future to swap in a PostgreSQL data layer, or is this reasonably trivial?
* are there any significant security risks in running a sqlite3 instance inside the Docker container (if we never expose the running port outside the container)?
* does this save us any money on the monthly bill now or in the anticipated future?

This is a reasonable question to ask.  The trade-off of not using the standard database may be worth the benefits we gain.

**Comment by znmeb** [comment]
Do you even need an RDBMS / Server? How much data is there for the MVP? A few hundred K compressed JSON is smaller than a lot of images! ;-) Maybe something like localStorage will work ... http://html5tutorial.net/tutorials/working-with-html5-localstorage.html ... or PouchDB https://pouchdb.com/

**Comment by jimtyhurst** [comment]
One reason for using a relational database is for the MVP to be an "executable architecture", i.e. we demonstrate how the target architecture for "real" budget data is supposed to work. Given the small amount of static data, we don't even need a web service for the MVP. We could just load JSON from static files with the UI as @znmeb suggests. While that could be a great first iteration of an MVP, most people in our team meetings seem to assume that we should have the UI get its data from web services. So why not go the extra step to let the web services access relational data from a database?

I see a continuum from releasing just a UI with static data files to a 2-layer implementation where the web services hold static data to a 3-layer implementation of UI, web services, and database. I think choosing a point on that continuum depends on our goals for the MVP. If the only goal or the primary goal is to demonstrate the UI, then there is no need for a database and I would argue that we should not even bother implementing web services. However, I want to participate in the project too, even if I am a backend developer, so I would like the MVP to demonstrate an API at least. From my limited knowledge of Django, the framework shines with a relational database. So I think it is worthwhile to implement all three layers as an example of the architecture that we are trying to get to, although adding a database definitely has the drawbacks mentioned by @MikeTheCanuck. 

Therefore, project scope should be the major factor in the decision. If we have enough money, time, and developer/devops knowledge to stand up a database, then let's do it, because it would be good to demonstrate the overall architecture. However, if we do not have enough money, time, or developer/devops knowledge to deploy a secure stand-alone database, then let's try using the default Django embedded database. If _that_ is too time consuming for devops or too insecure, then let's stick to the simplest prototype web service that we already have, which reads static data from a file and renders it with no transformations. We won't learn anything about Django or PostgreSQL, but we can still do some design of the API, which can carry forward to the next stage of development.

**Comment by znmeb** [comment]
@jimtyhurst I wouldn't worry about the DevOps or AWS hit; most of the projects are using Django and PostgreSQL on AWS so the only thing that would be unique to budget would be the contents of the database and the Django models / code. That would be an argument in *favor* of PostgreSQL - everyone else is using it so it's an "interchangeable part".

**Comment by MikeTheCanuck** [comment]
Well we've crossed the threshold to PostgreSQL for good or ill, so I'm closing this issue.
