### ISSUE TITLE
Ensure current API code is using PostgreSQL to retrieve requested data

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#43]
As of the ["secrets" branch](https://github.com/hackoregon/team-budget/pull/35), we are now enabling Budget team developers to configure their local instance of the Django app to use the AWS EC2-hosted PostgreSQL instance as the data layer.

The new configuration (from secrets branch) has no impact on the code in views.py (e.g. `find_ocrb_data()`, `find_kpm_data()`) that pulls in data through the local CSV files.  Thus work needs to be done to switch the API code so that each endpoint (e.g. `/kpm/`, `/ocrb/` and `/summary/`) pulls its data from whichever PostgreSQL instance (AWS or local) is currently configured in the running app.

**Comment by MikeTheCanuck** [comment]
Based on my testing today with the ["secrets" branch](https://github.com/hackoregon/team-budget/pull/35), I concluded that when we replaced sqlite3 with AWS-postgreSQL, the API must have been pulling data from postgres and not a local sqlite instance.  I may be wrong, and looking at the existing code I don't know how that would work exactly, but I am puzzled by the fact that I wiped out the reference to sqlite3 in `settings.py` and I was still able to get a response from each endpoint and that the response included all the data I expected to see.

To be tested: what happens when I break the `project_config.py` (e.g. give it a bad database password).

**Comment by mxmoss** [comment]
@MikeTheCanuck the version that you're testing with may still be pulling data from the CSV files

**Comment by jimtyhurst** [comment]
The two endpoints `OCRB` and `KPM` are still getting data from the CSV files. However, the `summary` endpoint gets its data from the database. I just tested pull request #35 and confirmed that the endpoint can draw data from the AWS EC2 instance of PostgreSQL, rather than the sqlite3 that I used originally during development of that `summary` endpoint.

**Comment by jimtyhurst** [comment]
I would leave this issue open until we have refactored the endpoints, so that `OCRB` and `KPM` get their data from the database, rather than reading from the CSV file. At that point, we can probably get rid of the `summary` endpoint, which is similar to `OCRB`, although it shows one way to do filtering and sorting, which goes beyond the current functionality of `OCRB`.

**Comment by jimtyhurst** [comment]
Closed by the merge of pull request #59. All endpoints now read data from whichever database is specified in the `project_config.py` file. I tested with the AWS EC2 instance running PostgreSQL and also tested with the configuration set for the embedded sqlite3 database. They both worked. Not at the same time, of course. But you can change the `project_config.py` and restart the server to access a different database.
