### ISSUE TITLE
Generate static data for use by initial CYOA API

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#7]
To generate the CYOA UI for users, the back end will take in the following as data inputs:

- spending by {Service Area, Bureau} by {"Quadrant"}
- citywide population
- "Quadrant" population

This means we'll need tabular data (probably rendered out to JSON) that captures this information.  Most or all of this data should be available from the Budget in Brief document.

**Comment by jimtyhurst** [comment]
This issue is partially resolved. There is static data derived from ["Budget in Brief" documents](https://drive.google.com/open?id=0B04ORgI23dk7MmFfYURrN05LTms) and historical budget data derived from a [database export](https://drive.google.com/open?id=0B7CgmR-dA_1KV2p6MzRaenM1VHc) provided by the City of Portland:

- [Budget_in_Brief_OCRB_data_All_Years.csv](https://github.com/hackoregon/team-budget/blob/master/Data/Budget_in_Brief_OCRB_data_All_Years.csv)
- [HackOregon_hx_budget_data_ASV2_transformed.csv](https://github.com/hackoregon/team-budget/blob/master/Data/HackOregon_hx_budget_data_ASV2_transformed.csv)

We think that is the most important data for the team's [Minimum Viable Product](https://drive.google.com/open?id=1BPNv1IE-8u1VX7fxwlPwxovIqZVtfRRqrjUCoOIlwOI) (MVP) being developed for the May 1 demo day. Unfortunately, we still do not have any population data or geographic data associated with the City of Portland's budget.

**Comment by MikeTheCanuck** [comment]
we're well past this point by now
